[package]
name = "ncuts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cannoli = { path = "../../cannoli" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
