[workspace]

resolver = "2"
members = [
    "mempipe",
    "cannoli",
    "cannoli_server",
    "examples/visualization",
    "examples/symbolizer",
    "examples/benchmark",
    "examples/benchmark_graph",
    "examples/secrecy",
    "examples/ncuts",
]

